variable "location" {}
variable "resource_group_name" {}
variable "tags" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "sku" {}
variable "name" {}
variable "public_network_access_enabled" {}
variable "no_public_ip" {}
variable "vnet_id" {}
variable "public_subnet_name" {}
variable "private_subnet_name" {}
variable "subscription_id" {}
variable "vnet_name" {}
variable "pe_subnet_id" {}
variable "vnet_rg_name" {}
variable "public_subnet_network_security_group_association_id" {}
variable "private_subnet_network_security_group_association_id" {}
