resource_group_name = "IC-Common-NonProd-RG"
location = "Central India"
vnet_name       = "IC-Common-NonProd-VNET"
vnet_rg_name    = "IC-Common-NonProd-RG"
pe_subnet_name  = "IC-Common-NonProd-VNET-QA-PE-SNET-01"
key_vault_name = "AZ01AKVQA01" 
subscription_id = "14ab3967-5405-4155-8149-cfe09d49cd37"
