variable "name" {}
variable "resource_group_name" {}
variable "location" {}
variable "sku" {}
variable "capacity" {}
variable "zone_redundant" {}
variable "local_authentication_enabled" {}
variable "public_network_access_enabled" {}
variable "subscription_id" {}
variable "vnet_name" {}
variable "storage_account_name" {}
variable "pe_subnet_id" {}
variable "vnet_rg_name" {}
variable "keyvault_id" {}
variable "tags" {}
variable "trusted_service_access_enabled" {}
variable "is_manual_connection" {}
variable "eventhub_raw_name" {}
variable "authorization_rule" {}
variable "consumer_group" {}
variable "adaniiotehwriter" {}
variable "eventhub_adaniiotehwriter_auth" {} 
variable "adaniiotehwriter_consumer" {}